service: aws-eks-spot-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  region: us-east-1

functions:
  videoUploadLambdaFunction:
    handler: upload_video.handler
    package:
      include:
        - upload_video/**
        - .kube/**
        - bin/**
      exclude:
        - ./**
    events:
      - s3:
          bucket: "aws-eks-spot-serverless-dev-uploads-linh"
          events:
            - s3:ObjectCreated:*
  thumbnailUploadLambdaFunction:
    handler: upload_thumbnail.handler
    events:
      - s3:
          bucket: "aws-eks-spot-serverless-dev-thumbnails-linh"
          events:
            - s3:ObjectCreated:*
