service: aws-eks-spot-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  region: us-east-1

functions:
  videoUploadLambdaFunction:
    handler: upload_video.handler
    events:
      - s3:
          bucket: "aws-eks-spot-serverless-dev-uploads"
          events:
            - s3:ObjectCreated:*
  thumbnailUploadLambdaFunction:
    handler: upload_thumbnail.handler
    events:
      - s3:
          bucket: "aws-eks-spot-serverless-dev-thumbnails"
          events:
            - s3:ObjectCreated:*


resources:
  Resources:
    ################
    #  EKS
    ################
    # VPC Setup
    KubernetesClusterVPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.0.0.0/16
        EnableDnsSupport: true
        EnableDnsHostnames: true
        Tags:
          - Key: Name
            Value: ${self:service}-${self:provider.stage}
    KubernetesClusterSubnetA:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref KubernetesClusterVPC
        CidrBlock: 10.0.0.0/24
        AvailabilityZone: us-east-1a
        Tags:
          - Key: Name
            Value: ${self:service}-${self:provider.stage}-subnet-a
    KubernetesClusterSubnetB:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref KubernetesClusterVPC
        CidrBlock: 10.0.1.0/24
        AvailabilityZone: us-east-1b
        Tags:
          - Key: Name
            Value: ${self:service}-${self:provider.stage}-subnet-b
    KubernetesClusterInternetGateway:
      Type: AWS::EC2::InternetGateway
      Properties:
        Tags:
          - Key: Name
            Value: ${self:service}-${self:provider.stage}
    KubernetesClusterInternetGatewayAttachment:
      Type: AWS::EC2::VPCGatewayAttachment
      Properties:
        VpcId: !Ref KubernetesClusterVPC
        InternetGatewayId: !Ref KubernetesClusterInternetGateway
    KubernetesClusterInternetGatewayRouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId: !Ref KubernetesClusterVPC
        Tags:
          - Key: Name
            Value: ${self:service}-${self:provider.stage}
    KubernetesClusterInternetGatewayToInternetRoute:
      Type: AWS::EC2::Route
      DependsOn:
        - KubernetesClusterInternetGateway
        - KubernetesClusterInternetGatewayAttachment
      Properties:
        RouteTableId: !Ref KubernetesClusterInternetGatewayRouteTable
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId: !Ref KubernetesClusterInternetGateway
    KubernetesClusterSubnetAtoInternetRouteAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId: !Ref KubernetesClusterInternetGatewayRouteTable
        SubnetId: !Ref KubernetesClusterSubnetA
    KubernetesClusterSubnetBtoInternetRouteAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId: !Ref KubernetesClusterInternetGatewayRouteTable
        SubnetId: !Ref KubernetesClusterSubnetB

    # SECURITY
    EksKubernetesServiceRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: EksKubernetesServiceRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - eks.amazonaws.com
              Action:
                - sts:AssumeRole
        ManagedPolicyArns:
          - 'arn:aws:iam::aws:policy/AmazonEKSClusterPolicy'
          - 'arn:aws:iam::aws:policy/AmazonEKSServicePolicy'
    # To protect EKS Master Management Port
    KubernetesClusterMasterSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Allow EKS Cluster communication with worker nodes
        VpcId: !Ref KubernetesClusterVPC
        #        SecurityGroupEgress:
        #          - IpProtocol: -1
        #            fromPort: -1
        #            toPort: -1
        #            CidrIp: 0.0.0.0/0
        Tags:
          - Key: Name
            Value: ${self:service}-${self:provider.stage}

    # OPTIONAL: Allow inbound traffic from your local workstation external IP
    #           to the Kubernetes. You will need to replace A.B.C.D below with
    #           your real IP. Services like icanhazip.com can help you find this.
    KubernetesClusterMasterFromWorkstationSecurityGroupRule:
      Type: AWS::EC2::SecurityGroupIngress
      Properties:
        #        CidrIp: A.B.C.D/32
        CidrIp: 104.28.119.144/32
        Description: Allow workstation to communicate with the EKS cluster API Server
        FromPort: 443
        IpProtocol: tcp
        ToPort: 443
        GroupId:
          Ref: KubernetesClusterMasterSecurityGroup

    # Create Cluster
    KubernetesCluster:
      Type: AWS::EKS::Cluster
      Properties:
        Name: ${self:service}-${self:provider.stage}
        ResourcesVpcConfig:
          SecurityGroupIds:
            - !Ref KubernetesClusterMasterSecurityGroup
          SubnetIds:
            - !Ref KubernetesClusterSubnetA
            - !Ref KubernetesClusterSubnetB
        RoleArn: !GetAtt EksKubernetesServiceRole.Arn
        Version: "1.25"


    ################
    #  WORKER NODE
    ################
    NodeInstanceRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: NodeInstanceRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - ec2.amazonaws.com
              Action:
                - sts:AssumeRole
        Path: "/"
        Policies:
          - PolicyName: node
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - ec2:Describe*
                    - ecr:GetAuthorizationToken
                    - ecr:BatchCheckLayerAvailability
                    - ecr:GetDownloadUrlForLayer
                    - ecr:GetRepositoryPolicy
                    - ecr:DescribeRepositories
                    - ecr:ListImages
                    - ecr:DescribeImages
                    - ecr:BatchGetImage
                  Resource: '*'
          - PolicyName: cni
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - ec2:DescribeNetworkInterfaces
                    - ec2:DescribeInstances
                    - ec2:AttachNetworkInterface
                    - ec2:CreateNetworkInterface
                    - ec2:DeleteNetworkInterface
                    - ec2:DetachNetworkInterface
                    - ec2:ModifyNetworkInterfaceAttribute
                    - ec2:AssignPrivateIpAddresses
                    - tag:TagResources
                  Resource: '*'
          - PolicyName: eks
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - eks:DescribeCluster
                  Resource: '*'
          - PolicyName: s3-management
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - s3:PutObject
                    - s3:GetObject
                    - s3:ListBucket
                    - s3:DeleteObject
                  Resource:
                    - '*' # Recheck
                - Effect: Allow
                  Action:
                    - s3:HeadBucket
                  Resource:
                    - '*'
          - PolicyName: ClusterAutoscaler
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - ec2:DescribeRegions
                    - ec2:DescribeInstances
                  Resource: '*'
                - Effect: Allow
                  Action:
                    - ecr:GetAuthorizationToken
                    - ecr:BatchCheckLayerAvailability
                    - ecr:GetDownloadUrlForLayer
                    - ecr:GetRepositoryPolicy
                    - ecr:DescribeRepositories
                    - ecr:ListImages
                    - ecr:BatchGetImage
                  Resource: '*'
                - Effect: Allow
                  Action:
                    - autoscaling:DescribeAutoScalingGroups
                    - autoscaling:DescribeAutoScalingInstances
                    - autoscaling:DescribeLaunchConfigurations
                    - autoscaling:SetDesiredCapacity
                    - autoscaling:DescribeTags
                    - autoscaling:TerminateInstanceInAutoScalingGroup
                  Resource: '*'

    # we need to describe AWS::IAM::InstanceProfile to provide EKS Nodes with appropriate permissions
    NodeInstanceProfile:
      Type: AWS::IAM::InstanceProfile
      Properties:
        Path: /
        Roles:
          - !Ref NodeInstanceRole
    NodeSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Security group for all nodes in the EKS cluster
        VpcId: !Ref KubernetesClusterVPC
        Tags:
          -
            Key: Name
            Value: ${self:service}-${self:provider.stage}

    NodeSecurityGroupIngress:
      Type: AWS::EC2::SecurityGroupIngress
      DependsOn: NodeSecurityGroup
      Properties:
        Description: Allow node to communicate with each other
        GroupId: !Ref NodeSecurityGroup
        SourceSecurityGroupId: !Ref NodeSecurityGroup
        IpProtocol: '-1'
        FromPort: 0
        ToPort: 65535
    NodeSecurityGroupFromWorkstationIngress:
      Type: AWS::EC2::SecurityGroupIngress
      DependsOn: NodeSecurityGroup
      Properties:
        Description: Allow workstation to connect to EC2 nodes (for debugging)
        GroupId: !Ref NodeSecurityGroup
        IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 104.28.119.144/32
    NodeSecurityGroupFromControlPlaneIngress:
      Type: AWS::EC2::SecurityGroupIngress
      DependsOn: NodeSecurityGroup
      Properties:
        Description: Allow worker Kubelets and pods to receive communication from the cluster control plane
        GroupId: !Ref NodeSecurityGroup
        SourceSecurityGroupId: !Ref KubernetesClusterMasterSecurityGroup
        IpProtocol: tcp
        FromPort: 1025
        ToPort: 65535
    KubernetesClusterMasterSecurityGroupIngressFromNodes:
      Type: AWS::EC2::SecurityGroupIngress
      DependsOn: NodeSecurityGroup
      Properties:
        Description: Allow pods to communicate with the cluster API Server
        GroupId: !Ref KubernetesClusterMasterSecurityGroup
        SourceSecurityGroupId: !Ref NodeSecurityGroup
        IpProtocol: tcp
        FromPort: 443
        ToPort: 443


    SpotNodeLaunchConfig:
      Type: AWS::AutoScaling::LaunchConfiguration
      Properties:
        AssociatePublicIpAddress: true # https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html
        IamInstanceProfile: !Ref NodeInstanceProfile
        ImageId: ami-0704d02231282bbe5
        InstanceType: m3.medium
        SpotPrice: 1
        SecurityGroups:
          - !Ref NodeSecurityGroup
        # Refer: https://repost.aws/knowledge-center/eks-worker-nodes-cluster
        UserData:
          Fn::Base64:
            Fn::Join:
              - ""
              -
                - "#!/bin/bash -xe\n"
                - "set -o xtrace"
                - "\n"
                - Fn::Join:
                  - " "
                  -
                    - "/etc/eks/bootstrap.sh"
                    - Ref: KubernetesCluster
                - "\n"
                - "/opt/aws/bin/cfn-signal -e $? "
                - "         --stack ${self:service}-${self:provider.stage} "
                - "         --resource NodeGroup "
                - "         --region ${self:provider.region}"

    SpotNodeGroup:
      Type: AWS::AutoScaling::AutoScalingGroup
      Properties:
        DesiredCapacity: 1
        LaunchConfigurationName: !Ref SpotNodeLaunchConfig
        MinSize: 0
        MaxSize: 2
        VPCZoneIdentifier:
          - !Ref KubernetesClusterSubnetA
          - !Ref KubernetesClusterSubnetB
        Tags:
          - Key: Name
            Value: ${self:service}-${self:provider.stage}
            PropagateAtLaunch: true
          - Key:
              Fn::Join:
                - "/"
                -
                  - "kubernetes.io"
                  - "cluster"
                  - "${self:service}-${self:provider.stage}"
            Value: 'owned'
            PropagateAtLaunch: 'true'
      UpdatePolicy:
        AutoScalingRollingUpdate:
          MinInstancesInService: 0
          MaxBatchSize: 1

  Outputs:
    KubernetesClusterName:
      Description: "EKS Cluster Name"
      Value: !Ref KubernetesCluster
    KubernetesClusterEndpoint:
      Description: Endpoint for your Kubernetes API server
      Value:
        Fn::GetAtt: [ KubernetesCluster, Endpoint ]
    KubernetesClusterCertificateAuthorityData:
      Description: Certificate authority data for your Kubernetes API server
      Value: !GetAtt KubernetesCluster.CertificateAuthorityData
    KubernetesClusterNodesRoleArn:
      Description: 'EKS Cluster Nodes Role Arn'
      Value: !GetAtt NodeInstanceRole.Arn