services:
  vpc:
    path: vpc
    params:
      vpcCidr: '10.90.64.0/19'
      privateSubnetOneCidr: '10.90.72.0/22'
      privateSubnetTwoCidr: '10.90.76.0/22'
      privateSubnetThreeCidr: '10.90.80.0/22'
      publicSubnetOneCidr: '10.90.64.0/24'
      publicSubnetTwoCidr: '10.90.65.0/24'
      publicSubnetThreeCidr: '10.90.66.0/24'

  eks:
    path: eks
    params:
      vpcId: ${vpc.vpcId}
      subnetOne: ${vpc.publicSubnetOneId}
      subnetTwo: ${vpc.publicSubnetTwoId}
      subnetThree: ${vpc.publicSubnetThreeId}
      infrastructureBaseSecurityGroup: ${vpc.infrastructureBaseSecurityGroupId}
      managedSgTxToolingBaseSecurityGroup: ${vpc.managedSgTxToolingBaseSecurityGroup}