services:
  vpc:
    path: vpc
    params:
      vpcCidr: '10.90.64.0/19'
      privateSubnetOneCidr: '10.90.72.0/22'
      privateSubnetTwoCidr: '10.90.76.0/22'
      privateSubnetThreeCidr: '10.90.80.0/22'
      publicSubnetOneCidr: '10.90.64.0/24'
      publicSubnetTwoCidr: '10.90.65.0/24'
      publicSubnetThreeCidr: '10.90.66.0/24'

  eks:
    path: eks
    params:
      eksVersion: 1.26
      eksClusterName: 'my-eks-cluster'
      vpcId: ${vpc.vpcId}
      subnetOne: ${vpc.privateSubnetOneId}
      subnetTwo: ${vpc.privateSubnetTwoId}
      subnetThree: ${vpc.privateSubnetThreeId}

#  bastion:
#    path: bastion-host
#    params:
#      vpcId: ${vpc.vpcId}
#      subnetOne: ${vpc.publicSubnetOneId}
#      subnetTwo: ${vpc.publicSubnetTwoId}
#      subnetThree: ${vpc.publicSubnetThreeId}
#      infrastructureBaseSecurityGroup: ${vpc.infrastructureBaseSecurityGroupId}
#      managedSgTxToolingBaseSecurityGroup: ${vpc.managedSgTxToolingBaseSecurityGroup}

  nat:
    path: nat-gateway
    params:
      subnetOne: ${vpc.publicSubnetOneId}
      privateRouteTableId: ${vpc.privateRouteTableId}

  eks-workers:
    path: eks-workers
    params:
      vpcId: ${vpc.vpcId}
      subnetOne: ${vpc.privateSubnetOneId}
      subnetTwo: ${vpc.privateSubnetTwoId}
      subnetThree: ${vpc.privateSubnetThreeId}
      infrastructureBaseSecurityGroup: ${vpc.infrastructureBaseSecurityGroupId}
      managedSgTxToolingBaseSecurityGroup: ${vpc.managedSgTxToolingBaseSecurityGroup}
      amiId: 'ami-01e4e3defef588e6b'
      amiIdInstanceType: t4g.small
      kubernetesClusterName: ${eks.KubernetesClusterName}
      kubernetesClusterEndpoint: ${eks.KubernetesClusterEndpoint}
      kubernetesClusterSecurityGroup: ${eks.KubernetesClusterMasterSecurityGroup}
      kubernetesClusterCertificateAuthorityData: ${eks.KubernetesClusterCertificateAuthorityData}
      kubernetesCluster: ${eks.KubernetesCluster}
