---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: myns
spec:
  selector:
    matchLabels:
      app: fastapi
  replicas: 1
  template:
    metadata:
      labels:
        app: fastapi
        fargate: enable
    spec:
      containers:
        - name: fastapi
          image: '992382721649.dkr.ecr.us-east-1.amazonaws.com/myapp:0.0.1'
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-dev
  namespace: myns
spec:
  type: NodePort
  selector:
    app: fastapi
  ports:
    - port: 8080
      nodePort: 32410
      protocol: TCP
      targetPort: 8080

