---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pynproc
  namespace: myns
spec:
  selector:
    matchLabels:
      app: pynproc
  replicas: 1
  template:
    metadata:
      labels:
        app: pynproc
        fargate: enable
    spec:
      containers:
        - name: pynproc
          image: '044737250745.dkr.ecr.us-east-1.amazonaws.com/pynproc:0.0.3'
#          command: ["/bin/bash", "-c", "echo 'ulimit -Sn 65535' >> /home/worker/.bashrc && echo 'ulimit -Su 65535' >> /home/worker/.bashrc && sleep 100"]
#      initContainers:
#        - name: init
#          image: alpine:latest
#          command: [ "sh", "-c", "echo 'ulimit -Sn 65535' >> /etc/.shrc && echo 'ulimit -Su 65535' >> /etc/.shrc && sleep 10" ]
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: pynproc-dev
  namespace: myns
spec:
  type: NodePort
  selector:
    app: pynproc
  ports:
    - port: 8080
      nodePort: 32411
      protocol: TCP
      targetPort: 8080
