---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pynproc
  namespace: myns
spec:
  selector:
    matchLabels:
      app: pynproc
  replicas: 1
  template:
    metadata:
      labels:
        app: pynproc
        fargate: enable
    spec:
      containers:
        - name: fastapi
          image: '992382721649.dkr.ecr.us-east-1.amazonaws.com/pynproc:0.0.1'
---
apiVersion: v1
kind: Service
metadata:
  name: pynproc-dev
  namespace: myns
spec:
  type: NodePort
  selector:
    app: pynproc
  ports:
    - port: 8080
      nodePort: 32410
      protocol: TCP
      targetPort: 8080

